disabled = false
languageCode = "de"
languageName = "German"
weight = 1
title = "🎱"

[params]
displayName = "de"
isoCode = "de"
rtl = false
dateFormat = "2. January 2006"

[params.author]
name = "Oliver Lange"
image = "ripndip.jpg"
#headline = ""
