[[main]]
none = "none"

[[main]]
name = "FiSi"
pre = "none"
pageRef = "FiSi"
weight = 10

[[main]]
name = "Doku"
pageRef = "FiSi/doku"
weight = 10

[[Aufgaben]]
name = "Aufgaben"
pageRef = "FiSi/aufgaben"
weight = 10

[[Projekt]]
name = "Projekt"
pageRef = "FiSi/projekt"
weight = 10

[[main]]
  name = "GitHub"
  url = "https://github.com/catalyys/catalyys.github.io"
  weight = 50
  pre = "<i class='fab fa-github'></i>"

[[footer]]
none = "none"
