#[[main]]
#none = "none"

[[main]]
name = "FiSi"
pageRef = "FiSi"
#identifier = "fNlQBUpsrl"
weight = 11

[[main]]
name = "Aufgaben"
pageRef = "FiSi/aufgaben"
weight = 10

[[main]]
name = "Projekt"
pageRef = "FiSi/projekt"
weight = 10

[[footer]]
none = "none"
