---
- hosts: all
  become: true
  vars:
    named: "prod_named.conf"
    zone: "azubi.dataport.de.zone"
    net: 1

  tasks:
    - include_tasks: tasks/common.yml
    - include_tasks: tasks/dns.yml
    - include_tasks: tasks/docker.yml


