---
- hosts: router
  vars:
    ansible_connection: network_cli
    ansible_network_os: vyos

  tasks:
    - name: configure l2 interfaces
      vyos.vyos.vyos_interfaces:
        config:
          - name: eth0
            description: virtual box nat
            enabled: true
          - name: eth1
            description: prod
            enabled: true
          - name: eth2
            description: test
            enabled: true
          - name: eth3
            description: entw
            enabled: true
          #- name: eth4
          #  description: Configured by Ansible
          #  enabled: true
        state: merged

    - name: configure l3 interfaces
      vyos.vyos.vyos_l3_interfaces:
        config:
          - name: eth0
            ipv4:
              - address: dhcp
          - name: eth1
            ipv4:
              - address: 10.100.1.254/24
          - name: eth2
            ipv4:
              - address: 10.100.2.254/24
          - name: eth3
            ipv6:
              - address: fd11:2:3:4::10/64
          #    - address: fd11:2:3:4::9/64
          #- name: eth4
          #  ipv4:
          #    - address: dhcp
          #  ipv6:
          #    - address: dhcpv6
        state: merged

    - name: filter out comments
      ansible.builtin.shell: |
        grep -v '^\s*#' configs/vyos/vyos.cfg | grep -v -e '^$'
      register: config
      delegate_to: localhost

    - name: configure vyos
      vyos.vyos.vyos_config:
        lines: "{{ config.stdout }}"

- hosts: clients
  become: true

  tasks:
    - include_tasks: tasks/common.yml
    - include_tasks: tasks/dns.yml
      when: "'dns' in group_names"
    - include_tasks: tasks/docker.yml
      when: "'docker' in group_names"
    - include_tasks: tasks/ipv6.yml
      when: v6 is defined


