Vagrant.configure("2") do |config|
 # ---------------- VyOs ----------------
  config.vm.define "vyos" do |vyos|
    vyos.vm.box = "vyos/current"

    vyos.vm.provider "virtualbox" do |vb|
      vb.name = "vyos"
      vb.memory = "512"
      vb.cpus = 2
    end

    vyos.vm.network "private_network", ip: "10.100.1.0", virtualbox__intnet: "prod"
    vyos.vm.network "private_network", ip: "10.100.2.0", virtualbox__intnet: "test"
    #config.vm.disk :disk, size: "20GB", primary: true
    #vyos.vm.network "private_network", type: "dhcp"

    vyos.vm.provision "ansible" do |ansible|
      ansible.playbook = "vyos.yml"
    end
  end

 # ---------------- Prod VM ----------------
  config.vm.define "client_prod" do |client_prod|
    client_prod.vm.box = "debian/bookworm64"

    client_prod.vm.provider "virtualbox" do |vb|
      vb.name = "client_prod"
      vb.memory = "512"
      vb.cpus = 2
    end

    #config.vm.disk :disk, size: "20GB", primary: true
    #client_prod.vm.network "private_network", type: "dhcp"
    client_prod.vm.network "private_network", type: "dhcp", virtualbox__intnet: "prod"

    client_prod.vm.provision "ansible" do |ansible|
      ansible.playbook = "client_prod.yml"
    end
  end

 # ---------------- Test VM ----------------
  config.vm.define "client_test" do |client_test|
    client_test.vm.box = "debian/bookworm64"

    client_test.vm.provider "virtualbox" do |vb|
      vb.name = "client_test"
      vb.memory = "512"
      vb.cpus = 2
    end

    #config.vm.disk :disk, size: "20GB", primary: true
    #client_test.vm.network "private_network", type: "dhcp"
    client_test.vm.network "private_network", type: "dhcp", virtualbox__intnet: "test"

    client_test.vm.provision "ansible" do |ansible|
      ansible.playbook = "client_test.yml"
    end
  end

 # ---------------- GLOBAL TRIGGER ----------------
  config.trigger.after :up do |trigger|
    trigger.name = "Run tests"
    #trigger.run = { path: "integration_tests.sh" }
    trigger.run = { inline: "pytest tests/integration_test.py" }
    trigger.only_on = "client_test"
  end
end

