---
- hosts: all
  vars:
    ansible_connection: network_cli
    ansible_network_os: vyos

  tasks:
    - name: configure l2 interfaces
      vyos.vyos.vyos_interfaces:
        config:
          - name: eth0
            description: Configured by Ansible
            enabled: true
          - name: eth1
            description: Configured by Ansible
            enabled: true
          - name: eth2
            description: Configured by Ansible
            enabled: true
        state: merged

    - name: configure l3 interfaces
      vyos.vyos.vyos_l3_interfaces:
        config:
          - name: eth0
            ipv4:
              - address: dhcp
          - name: eth1
            ipv4:
              - address: 10.100.1.254/24
          - name: eth2
            ipv4:
              - address: 10.100.2.254/24
        state: merged

    - name: filter out comments
      ansible.builtin.shell: |
        grep -v '^\s*#' configs/vyos/vyos.cfg | grep -v -e '^$'
      register: config
      delegate_to: localhost

    - name: debug
      debug:
        var: config

    - name: configure vyos
      vyos.vyos.vyos_config:
        lines: "{{ config.stdout }}"

