- name: delete default route on eth0
  command: "ip {{ v6 | default('') }} route del default dev eth0"

- name: delete default route on eth0
  command: "ip {{ v6 | default('') }} route del default dev eth1"
  when: v6 is defined

- name: add default route on eth1
  command: "ip {{ v6 | default('') }} route add default via {{ gateway }} dev eth1"

- name: change /etc/resolv.conf ipv4
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: |
      nameserver 1.1.1.1
      nameserver 1.0.0.1
    owner: root
    group: root
    mode: '0644'
  when: v6 is undefined

- name: change /etc/resolv.conf ipv6
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: |
      nameserver 2606:4700:4700::1111
      nameserver 2606:4700:4700::1001
    owner: root
    group: root
    mode: '0644'
  when: v6 is defined

- name: copy sources.list
  ansible.builtin.copy:
    src: "configs/sources.list"
    dest: "/etc/apt/sources.list"
    owner: root
    group: root
    mode: '0644'

