- name: update all packages to their latest version
  ansible.builtin.apt:
    update-cache: true
    upgrade: yes

- name: install packages
  apt:
    pkg:
      - fish
      - bind9
      - dnsutils
      - vim
      - curl
    state: present

- name: copy named.conf
  ansible.builtin.copy:
    src: "configs/dns/{{ named }}"
    dest: /etc/bind/named.conf
    owner: root
    group: bind
    mode: '0644'

- name: copy zone
  ansible.builtin.template:
    src: "configs/dns/{{ zone }}"
    dest: "/var/lib/bind/{{ zone }}"
    owner: root
    group: bind
    mode: '0644'

- name: restart named service
  ansible.builtin.service:
    name: named
    state: restarted

- name: change /etc/resolv.conf
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: |
      "nameserver {{ ansible_default_ipv4.address }}"
    owner: root
    group: root
    mode: '0644'
  when: v6 is undefined

- name: change /etc/resolv.conf
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: |
      "nameserver {{ ansible_default_ipv6.address }}"
    owner: root
    group: root
    mode: '0644'
  when: v6 is defined

