- name: change /etc/resolv.conf
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: |
      nameserver 64:ff9b::10.100.1.10
    owner: root
    group: root
    mode: '0644'
  when: v6 is defined

- name: update all packages to their latest version
  ansible.builtin.apt:
    update-cache: true
    #upgrade: yes

- name: install packages
  apt:
    pkg:
      - fish
      - vim
      - curl
      - nfs-common
    state: present

